global_theme: dark_theme
internal_theme: Gris oscuro 1
prede_font:
    editor-font: Consolas
    editor-size: 11
    result-font: Segoe UI
    result-size: 9
worldWrap: false
prede_geo:
- 0.10
- 0.10
- 0.60
- 0.80
result_geo:
- 70
- 70
- 70
- 70
- 70
- 70
splitter_geo:
- 0.55
- 0.45
- 0.80
- 0.20
splitter_geo_eco:
- 0.33
- 0.33
prede_dsn: IMPALA_PROD
path: null
