Compute stats: COMPUTE STATS {TABLE_NAME} ;
Drop table: DROP TABLE IF EXISTS {TABLE_NAME} PURGE ;
Copy table: "DROP TABLE IF EXISTS proceso.{TABLE_NAME} PURGE; \nCREATE TABLE proceso.{TABLE_NAME}\
  \ STORED AS PARQUET TBLPROPERTIES('transactional'='false') AS \nSELECT * \nFROM\
  \ {STARTING_ZONE}.{TABLE_NAME}; \n\nCOMPUTE STATS proceso.{TABLE_NAME};"
Create table: "DROP TABLE IF EXISTS {END_ZONE}.{TABLE_NAME} PURGE; \nCREATE TABLE\
  \ {END_ZONE}.{TABLE_NAME} STORED AS PARQUET TBLPROPERTIES('transactional'='false')\
  \ AS \nSELECT * \nFROM {STARTING_ZONE}.{TABLE_NAME}; \n\nCOMPUTE STATS {END_ZONE}.{TABLE_NAME};"
Duplicates validation: "SELECT {VAR}, COUNT(1) \nFROM \nWHERE ingestion_year = XXX\
  \ and ingestion_month = XXX and ingestion_day = XXX \nGROUP BY 1 \nHAVING COUNT(1)\
  \ > 1"
Group by ingestions: GROUP BY ingestion_year, ingestion_month, ingestion_day
Ingestions: ' ingestion_year, ingestion_month, ingestion_day'
Ingestions bigint: (ingestion_year*10000 + ingestion_month*100 + ingestion_day)
On of joins: 'ON CAST(t1. as bigint) = CAST(t2. as bigint) AND CAST(t1. as bigint)
  = CAST(t2. as bigint) '
Order by ingestions: ORDER BY ingestion_year DESC, ingestion_month DESC, ingestion_day
  DESC
Row number: ROW_NUMBER() OVER (PARTITION BY {VAR} ORDER BY ingestion_year DESC, ingestion_month
  DESC, ingestion_day DESC) AS rn
Select from: "SELECT \nFROM \nWHERE ingestion_year = {PARAM_YEAR} AND ingestion_month\
  \ = {PARAM_MONTH} \nORDER BY  ingestion_year DESC, ingestion_month DESC, ingestion_day\
  \ DESC \nLIMIT  100;"
Stored as parquet: STORED AS PARQUET TBLPROPERTIES('transactional'='false') AS
