command_format:
- ADD
- ALL
- ALTER
- AND
- AS
- ASC
- BETWEEN
- BIGINT
- BOOLEAN
- BY
- CHAR
- COLUMNS
- COMPUTE
- CREATE
- DATABASES
- DECIMAL
- DELETE
- DESC
- DESCRIBE
- DISTINCT
- DOUBLE
- DROP
- EXISTS
- EXPLAIN
- FLOAT
- FOREIGN
- FORMATTED
- FROM
- FULL
- GRANT
- GROUP
- HAVING
- IF
- IN
- INDEX
- INNER
- INSERT
- INT
- INTO
- JOIN
- LEFT
- LIKE
- LIMIT
- MODIFY
- NOT
- 'ON'
- OR
- ORDER
- PARQUET
- PARTITION
- PARTITIONS
- PARTITIONED
- PRIMARY
- PURGE
- REVOKE
- RIGHT
- SELECT
- SET
- SHOW
- SMALLINT
- STATS
- STORED
- STRING
- TABLE
- TABLES
- TBLPROPERTIES
- TIMESTAMP
- TINYINT
- UNION
- UPDATE
- USE
- USING
- VALUES
- VARCHAR
- WHERE
- WITH
operator_format:
- ABS
- ACOS
- ADD_MONTHS
- ASIN
- ATAN
- AVG
- SUBSTR
- CASE
- CAST
- CEIL
- COALESCE
- CONCAT
- COS
- COUNT
- CURRENT_DATE
- CURRENT_TIMESTAMP
- DATE_ADD
- DATE_FORMAT
- DATE_SUB
- DATEDIFF
- DENSE_RANK
- DTRUNC
- ELSE
- END
- EXP
- 'FALSE'
- FIRST_VALUE
- FLOOR
- IS
- LAG
- LENGTH
- LOG
- LOWER
- LTRIM
- MAX
- MIN
- NTILE
- 'NULL'
- NVL
- OVER
- POWER
- RANK
- ROUND
- ROW_NUMBER()
- RTRIM
- SIN
- SQRT
- STDDEV
- SUBSTRING
- SUM
- TAN
- THEN
- TIMESTAMPDIFF
- TRIM
- 'TRUE'
- UPPER
- WHEN
- MONTH
- DAY
- YEAR
